import React, {useEffect,useState} from 'react';
import {api,money} from '../service';
export function Compliance({reservations,reload}:{reservations:any[],reload:()=>Promise<void>}) {
 const [data,setData]=useState<any>(null),[message,setMessage]=useState(''),[busy,setBusy]=useState(false);
 const load=()=>api('/admin/compliance').then(setData);
 useEffect(()=>{load().catch(e=>setMessage(e.message));},[]);
 async function run(fn:()=>Promise<unknown>){setBusy(true);try{await fn();await load();await reload();setMessage('Registro salvo.');}catch(e){setMessage((e as Error).message);}finally{setBusy(false);}}
 function form(e:React.FormEvent<HTMLFormElement>){e.preventDefault();return new FormData(e.currentTarget);}
 if(!data)return <p role="status">{message||'Carregando…'}</p>;
 return <div className="space-y-6"><p role="status">{message}</p>
 <section className="surface space-y-3"><h2 className="font-bold">Aprovação jurídica: {data.approval.approved&&data.approval.term_hash===data.termHash?'registrada':'pendente'}</h2>
 <p>Versão {data.version}. A confirmação exige aprovação desta versão, termo assinado validado e sinal de 20% recebido.</p>
 <a className="underline" href="/api/admin/term-template">Baixar minuta para revisão jurídica</a>
 <form className="grid gap-3" onSubmit={e=>{const f=form(e);void run(()=>api('/admin/legal-approval','POST',{termHash:data.termHash,approved:true,confirmedReview:f.get('review')==='on',reviewer:f.get('reviewer'),reference:f.get('reference')}));}}>
 <label>Responsável jurídico<input name="reviewer" required minLength={3}/></label><label>Referência do parecer de aprovação<input name="reference" required minLength={5}/></label>
 <label className="check-label"><input name="review" type="checkbox" required/>Confirmo que o jurídico aprovou esta versão integral para uso.</label>
 <button className="action" disabled={busy}>Registrar aprovação já concedida</button></form>
 <button className="underline" disabled={busy} onClick={()=>run(()=>api('/admin/legal-approval','POST',{termHash:data.termHash,approved:false}))}>Suspender uso do termo</button></section>
 <form className="surface grid gap-3" onSubmit={e=>{const f=form(e);void run(()=>api('/admin/banking','PUT',Object.fromEntries(f)));}}><h2 className="font-bold">Pix e transferência bancária</h2><p>Dados em branco até o cadastro. Confira a titularidade antes de publicar.</p>
 {Object.entries({bank:'Banco',holder:'Titular',holderDocument:'CPF do titular',branch:'Agência',account:'Conta com dígito',accountType:'Tipo de conta',pixKey:'Chave Pix'}).map(([key,label])=><label key={key}>{label}<input name={key} defaultValue={data.bank[key]} maxLength={150}/></label>)}<button disabled={busy} className="action">Salvar dados bancários</button></form>
 <h2 className="font-bold">Termos por pedido</h2><p>Preencha todas as lacunas no termo, gere o PDF e encaminhe para assinatura. Valide o PDF original no <a className="underline" href="https://validar.iti.gov.br/" target="_blank" rel="noreferrer">VALIDAR do ITI</a>. O sistema registra a conferência humana; não realiza verificação criptográfica.</p>
 {reservations.filter(r=>r.status==='requested').map(r=><article className="surface space-y-3" key={r.id}><h3 className="font-bold">{r.name} · {r.check_in} · {r.id}</h3><p>Termo: {r.requirements.signatureReady?'validado':'pendente'} · sinal exigido: {money(r.requirements.requiredDepositCents)} · recebido conferido: {money(r.requirements.paidCents)}</p>
 <a className="underline" href={`/api/admin/reservations/${r.id}/term`}>Baixar termo com dados do pedido</a>
 <form className="grid gap-3" onSubmit={e=>{const f=form(e);void run(async()=>{const file=f.get('pdf') as File;if(!file.size||file.size>5*1024*1024)throw Error('Envie PDF de até 5 MB.');const base64=await new Promise<string>((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>resolve(String(reader.result).split(',')[1]);reader.onerror=()=>reject(Error('Falha ao ler arquivo.'));reader.readAsDataURL(file);});return api(`/admin/reservations/${r.id}/signed-term`,'POST',{base64});});}}><label>PDF original assinado (até 5 MB)<input name="pdf" type="file" accept="application/pdf,.pdf" required/></label><button disabled={busy} className="action">Anexar PDF e aguardar validação</button></form>
 {r.requirements.documentHash&&<><a className="underline" href={`/api/admin/reservations/${r.id}/signed-term`}>Baixar original para validar</a><p className="break-all text-xs">SHA-256: {r.requirements.documentHash}</p>
 <form className="grid gap-3" onSubmit={e=>{const f=form(e);void run(()=>api(`/admin/reservations/${r.id}/validate-term`,'POST',{sha256:r.requirements.documentHash,reviewer:f.get('reviewer'),reference:f.get('reference'),signatureChecked:f.get('signature')==='on',identityChecked:f.get('identity')==='on',contentChecked:f.get('content')==='on'}));}}>
 <label>Responsável pela conferência<input name="reviewer" required minLength={3}/></label><label>Referência do relatório de validação<input name="reference" required minLength={5}/></label>
 {Object.entries({signature:'Assinatura e integridade verificadas no validador oficial.',identity:'Identidade do signatário corresponde ao hóspede contratante.',content:'Documento contém a versão aprovada, valores, datas, horários e todas as lacunas preenchidas.'}).map(([key,label])=><label className="check-label" key={key}><input name={key} type="checkbox" required/>{label}</label>)}
 <button disabled={busy||!r.requirements.legalReady} className="action">Registrar validação realizada</button></form></>}
 </article>)}
 </div>;
}
export function PaymentSection(){const [data,setData]=useState<any>(null),[error,setError]=useState('');useEffect(()=>{api('/payment-options').then(setData).catch(e=>setError(e.message));},[]);return <section id="pagamento" className="py-8 border-t space-y-3"><h2 className="section-title">Pix e transferência</h2><p>A reserva será efetivada somente após a assinatura e validação do termo de compromisso, o recebimento do sinal de 20% e a confirmação de disponibilidade pela administração.</p>{error?<p role="alert">Não foi possível consultar as opções de pagamento.</p>:!data?<p>Consultando opções…</p>:<>{!data.pixAvailable&&!data.transferAvailable?<p>Dados bancários ainda não disponibilizados. Aguarde as orientações da administração antes de pagar.</p>:<><p>Use os dados abaixo somente após receber o termo aprovado e as orientações para o seu pedido. Guarde o protocolo da reserva.</p>{data.pixAvailable&&<p className="break-all">Chave Pix: <strong>{data.bank.pixKey}</strong></p>}{data.transferAvailable&&<p>Banco: {data.bank.bank} · Agência: {data.bank.branch} · Conta: {data.bank.account} · {data.bank.accountType}</p>}<p>Titular: {data.bank.holder} · CPF: {data.bank.holderDocument}</p><p>O envio do comprovante não confirma o recebimento. Aguarde a conferência e a confirmação da reserva.</p></>}</>}</section>;}
